name: MyFalskApp CI

on:
  push:
    branches: develop

jobs:
	build:
		runs-on: ubuntu-latest		
  		
		steps:
			- name: Checkout Code
		   uses: actions/checkout@v4
		 
			- name: Setup Python
		   uses: actions/setup-python@v3
		   with:
		     python-version: 3.11
			- name: Create Virtual env
		   run: |
		   	python -m venv venv
		   	source venv/bin/activate

		 - name: Install Dependencies
		   run: |
		   	python -m pip install --upgrade pip
		   	python -m pip install --upgrade pip
        	pip install flake8 pytest
        	if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

		 - name: Print Debugging Information
		   run: |
		   	echo "Python Versoin: $(python --version)"
		   	echo "Working Directory: $(pwd)"
		   	echo "Content of Working Directory: $(ls -l)"
		   	echo "Content of sites-packages: $(ls -l venv/lib/python*/site-packages)"
		 
		 - name: Lint with flake8
	       run: |
	        # stop the build if there are Python syntax errors or undefined names
	        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
	        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
	        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
		 - name: Run Unit tests
		   run: python test_unit_cases.py
